/**
 * Created by pdamerval on 10/3/2016.
 */
var RACE = {
  K: "NATIVE AK/CUP'IK",	L: "NATIVE AMERICAN",	A: "ASIAN/PACIFIC ISLAND",
  B: "BLACK",	W: "CAUCASIAN",	U: "UNKNOWN",	I: "INDIAN",
  H: "HISPANIC/LATINO",	N: "NATIVE AK/UNK TRIBE",	C: "NATIVE AK/ATHABASKAN",
  D: "NATIVE AK/TLINGIT",	E: "NATIVE AK/HAIDA",	F: "NATIVE AK/ALEUT",
  G: "NATIVE AK/INUPIAT",	J: "NATIVE AK/YUP'IK",	O: "NATIVE AK/TSIMSHIAN",
  P: "ASIAN",	Q: "NATIVE AMERICAN/ALAS",	R: "PACIFIC NATIVE",
  S: "OTHER/UNKNOWN"
};