/**
 * Created by pdamerval on 10/3/2016.
 */
var RELIGION = {
  '00': "NONE",	'01': "ASSEMBLIES OF GOD",	'02': "ISLAM",	'03': "BAPTIST",	'04': "CATHOLIC",
  '05': "BUDDHIST",	'06': "EPISCOPAL",	'07': "CHRISTIAN SCIENCE",	'08': "PENTECOSTAL",
  '09': "JEHOVAH'S WITNESS",	10: "JEWISH",	11: "METHODIST",	12: "LUTHERAN",	13: "LDS/MORMON",
  14: "NATIVE AMERICAN",	15: "NONDENOM CHRISTIAN",	16: "SHARED MINISTRIES",
  17: "SEVENTH DAY ADVENTIST",	18: "WORLDWIDE CHURCH OF GOD",	19: "PRESBYTERIAN",
  20: "CHURCH OF CHRIST",	99: "UNKNOWN",	21: "DISCIPLES OF CHRIST",
  22: "EVANGELICAL CONVENANT",	23: "GREEK ORTHODOX",	24: "NAZARENE",	25: "FRIENDS (QUAKERS)",
  26: "RUSSIAN ORTHODOX",	27: "UNITARIAN UNIVERSALIST",	28: "OTHER",	29: "BRETHREN",
  30: "FREE METHODIST",	31: "ALLIANCE BIBLE",	32: "BIBLE CHURCH",	33: "CHRISTIAN METH EPISCOPAL",
  34: "CHURCH OF GOD",	35: "CHURCH OF GOD IN PROPHECY",	36: "MENNONITE",
  37: "MORAVIAN",	38: "SALVATION ARMY",	39: "WESLEYAN",	40: "BAHA'I",
  41: "CHURCH OF RELIGIOUS SCI",	42: "ECKANKAR",	43: "REFORMED LDS",
  44: "CHRISTIAN CHURCH",	45: "DRUID",	46: "WICCAN"
};
